# Generated by Django 5.0.2 on 2024-04-04 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_recipeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_image', to='ledger.recipe'),
        ),
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
