# Generated by Django 5.0.2 on 2024-04-04 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_alter_recipeimage_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
